### ISSUE TITLE
Iris trying to call iris-time even if the service is not registered 

### ISSUE THREAD

**Issue by oriassaraf** [oriassaraf/iris#2]
get the following error

{ Error: connect ECONNREFUSED ::ffff:127.0.0.1:55777
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::ffff:127.0.0.1',
  port: 55777,
  response: undefined }

**Comment by oriassaraf** [comment]
_cleanup is not being called at all when Iris-time is turned off.

**Comment by oriassaraf** [comment]
Fix in d879bec75273d6c161b778288ab035f48046e621
